name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Lint + formato
        run: pnpm lint

      - name: Type-check (Astro + TS)
        run: pnpm astro check

      - name: Unit tests
        run: pnpm test -- --run

      - name: Build de producción
        run: pnpm build
