name: CI
on: [push]
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install && pnpm add -g @lhci/cli@0.15.x
        run: pnpm build
        run: lhci autorun

